version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: banco
    ports:
      - "5432:5432"
    volumes:
      - ./DDL.sql:/docker-entrypoint-initdb.d/DDL.sql
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
